name: lint test deploy
on: [push]
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: dependency
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: deploy
        run: npm run build
