name: separate jobs
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: dependency
        run: npm install
      - name: lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: dependency
        run: npm install
      - name: test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: dependency
        run: npm install
      - name: deploy
        run: npm run build
